spring.application.name=grocery-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=${SECRET}
jwt.expiration=${EXPIRY}
cloudinary.cloud-name=${CLOUD_NAMECLO}
cloudinary.api-key=${API_KEYCLO}
cloudinary.api-secret=${API_SECRETCLO}